In [1]:
import math

In [2]:
math.cos(45)

0.5253219888177297

In [3]:
math.pow(2,10)

1024.0

In [4]:
import random

In [5]:
random.random()

0.4512845582273435

In [6]:
import random  as r

In [7]:
r.random()  ##0~1사이의 무작위 값

0.5373471690031552

In [8]:
for _ in range(10):
    print(r.randrange(5), end='')  ##0~4까지

3020243133

In [9]:
for _ in range(10):
    print(r.randrange(2, 7), end='')  ##2~6까지

6646362364

In [10]:
for _ in range(10):
    print(r.randint(2, 7), end='')  ##2~7까지

2273472563

In [11]:
a=[5,7,2,5,7,2.5, 9,8]
for _ in range(5):
    r.shuffle(a)  ## a리스트의 값들을 무작위로 섞기
    print(a)
print("끝")    

[8, 5, 7, 2.5, 2, 5, 9, 7]
[2.5, 5, 9, 7, 8, 2, 5, 7]
[8, 2, 5, 7, 5, 7, 9, 2.5]
[5, 8, 7, 5, 7, 9, 2.5, 2]
[9, 5, 2.5, 2, 8, 5, 7, 7]
끝


In [12]:
r.choice(a)  ## 무작위로 임의값을 1개 추출

5

##### List 단점
- 수로만 구성되어도 수가 아닌 단순한 값의 나열로 취급
- 숫자 연산이 불가

##### 내부(기본) 라이브러리
- 별도로 설치X
- math, random, turtle....

##### 외부 라이브러리
- 파이썬의 외부 라이브러리
- 설치 : pip~~~
- 쥬피터노트북은 설치 x 
- numpy, pandas, matplotLib....

## Numpy
- 수로 구성 : 배열로 해석
- 1차원 ~~ n차원 : 행과 열이 구성
- 리스트랑 비슷
- 다른점 : 수학적 계산
- 인덱싱, 슬라이싱
- 배열값 : 행 전체가 다른 행이랑 변경이 되거나, 
-          열이 다른 열이랑 변경이 되어도 배열값은 변하지 않고 배열값은 동일

In [13]:
import numpy as np

In [14]:
list = [1, 2, 10]  ## 리스트
print(list * 3)    ## 연산 불가 - 3번 반복 출력

[1, 2, 10, 1, 2, 10, 1, 2, 10]


In [15]:
arr = np.array(list)  ##numpy 연산이 가능한 배열
print(arr * 3)
print(arr + 100)
print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.dtype)

[ 3  6 30]
[101 102 110]
(3,)
3
1
int32


In [16]:
a=5.0
b=4
type(a), type(b)

(float, int)

In [17]:
data = [   [1,2,3],   [4,5,6],  [7,8,9], [5,6,4]  ]
data2 = [   [1,2,3],   [4,5,6],  [7,8,9]  ]
print(data+data2)
print(data)
type(data)  ##type : 데이터형

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [5, 6, 4], [1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1, 2, 3], [4, 5, 6], [7, 8, 9], [5, 6, 4]]


list

In [18]:
arr = np.array(data) ## 맨앞뒤에 []로 나오는 것은 그냥 그 자체가 배열 의미
  ## 안쪽의 []는 행을 의미
print(arr)
type(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [5 6 4]]


numpy.ndarray

In [19]:
arr2 = np.array(data)
arr3 = arr+arr2
arr3

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18],
       [10, 12,  8]])

In [20]:
arr.dtype

dtype('int32')

In [21]:
arr.shape  ## ?행 ?열인지?

(4, 3)

In [22]:
arr.ndim

2

In [23]:
arr.size

12

In [24]:
arr.itemsize

4

In [25]:
arr.data

In [26]:
a1=np.array([1,2,3])
a2=np.array([ [1,2,3,4], [5, 6, 7, 8] ])
print(a1)
print(a2)

[1 2 3]
[[1 2 3 4]
 [5 6 7 8]]


In [27]:
a1[2]

3

In [28]:
a2[0,0], a2[0][0]

(1, 1)

a2[ ,2]   ## 모든 행의 2열만 나오라는 것
- 행 생략으로 인해 문법적 오류

In [29]:
a2[ : , 2]

array([3, 7])

In [30]:
a2[1,]

array([5, 6, 7, 8])

In [31]:
a2[1: , :2]  ## 1행부터 마지막행까지
             ## 0열부터 1열까지   겹치는 부분 출력

array([[5, 6]])

In [32]:
np.zeros((2,3))
## 파이썬의 기본은 실수형으로 처리

array([[0., 0., 0.],
       [0., 0., 0.]])

In [33]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [34]:
x = range(5)   ## 범위
print(type(x)) 
x  

<class 'range'>


range(0, 5)

In [35]:
y = np.arange(5)  ##넘파이가 제공하는 값의 배열
print(type(y)) ; y

<class 'numpy.ndarray'>


array([0, 1, 2, 3, 4])

In [36]:
z = y.astype(np.float32) ; z    # astype : 데이터형식을 변경

array([0., 1., 2., 3., 4.], dtype=float32)

In [37]:
data = np.arange(12).reshape(4, 3)
# np.arange(12)  <- 1차원배열
# reshape(4,3)   <-4행 3열로 배열 모양 변경
data  ##print 생략시 변수가 가지고 있는 값을 그대로 출력

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [38]:
type(data)

numpy.ndarray

In [39]:
data > 5  ## data 배열의 원소중 5보다 크면 true, 그 외는 false

array([[False, False, False],
       [False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [40]:
data[data > 5] = 7   ## data배열의 True값을 가지는 원소를 7로 배정
data

array([[0, 1, 2],
       [3, 4, 5],
       [7, 7, 7],
       [7, 7, 7]])

In [41]:
data = np.arange(12).reshape(4, 3)
data 

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [42]:
data.mean()

5.5

In [43]:
data.mean(axis=1)  ## 행단위 평균을 계산

array([ 1.,  4.,  7., 10.])

In [44]:
data.mean(axis=0) ## 열단위 평균을 계산

array([4.5, 5.5, 6.5])

In [45]:
data[0]

array([0, 1, 2])

In [46]:
data[  [0]   ]

array([[0, 1, 2]])

In [47]:
data[ [1,0] ]

array([[3, 4, 5],
       [0, 1, 2]])

In [48]:
data[  [3,2,0,1]  ]

array([[ 9, 10, 11],
       [ 6,  7,  8],
       [ 0,  1,  2],
       [ 3,  4,  5]])

In [49]:
data

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [50]:
data[ [3,2,1,0]  ]   [:,[2,1,0]]

array([[11, 10,  9],
       [ 8,  7,  6],
       [ 5,  4,  3],
       [ 2,  1,  0]])

In [51]:
data.T   ##전치배열 - 행과열을 변경 : 1행3열  -> 3행1열로 변경

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [52]:
np.dot(data,data.T)  ##dot *(행렬 자체 곱)
### 수학적인 행렬의 자체 수학적 곱셈.  np.dot함수가 처리

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [53]:
b1=np.array([ [1,2,3], [4, 5, 6] ]) ##2행 3열의 배열
b2=np.array([ [1,2,3], [4, 5, 6] ]) ##2행 3열의 배열

b3=np.array([ [1,2],   [3,4],     [5, 6] ])  ## 3행 2열

print(b1+b2)
##  print(b1+b3)   : 행렬의 사칙연산은 크기가 동일해야 함

print(b1*b2)

### 수학적인 행렬의 곱셈은 정방행렬이거나, 
## 앞배열의 행의수와 뒷배열의 열의수가 동일해야지 계산이 됨

### print(np.dot(b1, b2))  --> 행, 열 크기가 달라서 오류
print(np.dot(b1, b3))  ## --> b1은 2행3열 b3는 3행 2열

[[ 2  4  6]
 [ 8 10 12]]
[[ 1  4  9]
 [16 25 36]]
[[22 28]
 [49 64]]


In [54]:
a=np.arange(1,10,2)
a

array([1, 3, 5, 7, 9])

In [55]:
x = np.array([1,2,3,4,5,6])
(x>4).sum()   ##4보다 큰 데이터의 갯수

2

In [56]:
print(data)
print(type(data))
print(type(x))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [58]:
(data>1).sum()
#- 리스는 합 계산 sum이 안 된다. 
#- 넘파이 배열은 합 계산 sum이 된다. 

10

In [ ]:
(x>4)

In [ ]:
z = np.random.randint(0,100, 10) ## 0~100을 포함한 값 사이의 랜덤값을 10개 추출
z

In [ ]:
z.sort() ; z

In [ ]:
np.sort(z) ##오름차순

In [ ]:
np.sort(z)[::-1] ##내림차순

In [ ]:
np.random.permutation(z)  ## 넘파이 z 값을 섞기

In [ ]:
t = np.array([[8,4,11,5],[2,10,7,3],[9,12,1,6]])  ; t

In [ ]:
t.sort(1) ; t  ## 한개의 행에서 정렬

In [ ]:
t.sort(0) ; t  ## 한개의 열에서 정렬

In [ ]:
t.sort() ; t

-- 문법적으로 안 됨
np.linspace(0, 1, 12, size=(3,4))

-- 해결
q=np.linspace(0, 1, 12)
q.reshape(3, 4)

In [ ]:
print(np.linspace(0, 100, 5))  ## 0~100 사이의 균일한 간격으로 5개 추출
print(np.linspace(0, 1, 9))  ## 0~1 사이의 균일한 간격으로 5개 추출
print(np.linspace(0, 1))
q=np.linspace(0, 1, 12)
print(q.reshape(3, 4))

In [ ]:
print(np.logspace(0, 5, 3))  ##10의0승부터 10의5승 사이의 균일한 간격으로 3개 추출
q=np.logspace(0, 4, 6)
print(q.reshape(3,2))

In [ ]:
np.random.seed(50)  ## 랜덤값을 초기화 - 50번에 해당하는 랜덤값을 받기

In [ ]:
np.random.seed(50)
for _ in range(3):
    print(np.random.rand(5))  ## 0~1사이의 무작위 수를 추출

In [ ]:
for _ in range(3):
    print(np.random.randn(5))  
    ## -1~1사이의 근처에 평균이 0이고, 표준편차가 1인 무작위 수를 추출
np.random.randn(3,4)    

In [ ]:
for _ in range(3):
    print(np.random.randint(2, 100, size=(2,3)))